### ISSUE TITLE
2EventStoreSubscriptionManagement was in project accounts-command-side-service

### ISSUE THREAD

**Issue by dimboyNew** [cer/event-sourcing-examples#20]
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [net.chrisrichardson.eventstore.EventStoreSubscriptionManagement] is defined: expected single matching bean but found 2: eventStore,jdbcEventStore
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1054)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 27 more

**Comment by cer** [comment]
Please can you provide more information.
What exactly are you running? And, how?

**Comment by dimboyNew** [comment]
Project: /event-sourcing-examples/accounts-command-side-service
IDE： eclipse
Operation: just run as an java application, with env arguments:
-- Project and main class

[image: 内嵌图片 1]

-- arguments
[image: 内嵌图片 2]


2016-07-20 11:14 GMT+08:00 Chris Richardson <notifications@github.com>:

**Comment by dimboyNew** [comment]
hi ,
is it sufficient with these pictures and comments?

hope your reply

dim

2016-07-20 12:49 GMT+08:00 New Wang <dimboynew@gmail.com>:

**Comment by cer** [comment]
Sorry for the delayed response.
Eclipse has an issue with classpaths.
If Module X depends on Module Y, which has testCompile dependency on artifact Z then Z is exported from Y and visible to X.
This results in a conflict.

A new version of the Eventuate Client (+ minor change to example code) in the near future should address this problem.

In the meantime, please run from the command line
