### ISSUE TITLE
Issue while starting the client

### ISSUE THREAD

**Issue by surajpanda1582** [cer/event-sourcing-examples#35]
I am getting below exception now while starting client. Can you please tell me what's wrong here.Below are my configuration

I have started my local zookeper, kafka server and MySql server.
I have created below topics in kafka
com.so.aggregate.BidAggregate
com.so.aggregate.ItemAggregate
eventuate.local.cdc.my-sql-connector.history.kafka.topic
eventuate.local.cdc.my-sql-connector.offset.storage
Created events,entities and snapshots table in eventuate schema. 
Also one more query I have included embeded CDC in my client application. DO I need to separately run local CDC service?

java.util.concurrent.ExecutionException: java.lang.RuntimeException: Engine failed to startUnable to configure and start the 'org.apache.kafka.connect.storage.KafkaOffsetBackingStore' offset backing store
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_141]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[na:1.8.0_141]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:69) [eventuate-local-java-embedded-cdc-0.11.0.RELEASE.jar:na]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay$1.takeLeadership(EventTableChangesToAggregateTopicRelay.java:61) [eventuate-local-java-embedded-cdc-0.11.0.RELEASE.jar:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:537) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:399) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:444) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245) [curator-recipes-2.11.1.jar:na]
	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239) [curator-recipes-2.11.1.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_141]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: java.lang.RuntimeException: Engine failed to startUnable to configure and start the 'org.apache.kafka.connect.storage.KafkaOffsetBackingStore' offset backing store
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$0(EventTableChangesToAggregateTopicRelay.java:165) ~[eventuate-local-java-embedded-cdc-0.11.0.RELEASE.jar:na]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:793) ~[debezium-embedded-0.7.5.jar:0.7.5]
	at io.eventuate.local.cdc.debezium.EventTableChangesToAggregateTopicRelay.lambda$startCapturingChanges$1(EventTableChangesToAggregateTopicRelay.java:174) ~[eventuate-local-java-embedded-cdc-0.11.0.RELEASE.jar:na]
	... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.configure(KafkaOffsetBackingStore.java:82) ~[connect-runtime-1.0.1.jar:na]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:628) ~[debezium-embedded-0.7.5.jar:0.7.5]
	... 4 common frames omitted

**Comment by surajpanda1582** [comment]
Actually these two parameter value not defined in debezium-embedded jar thats why throwing null pointer exception. However my client application gets starts. But the events are not publishing to accountviewservice. So suspecting this could be the issue. Can you please take a look

**Comment by surajpanda1582** [comment]
MySqlBinLogBasedEventTableChangesToAggregateTopicRelay.java doesn't have configuration properties of 
offset.storage.partitions
offset.storage.replication.factor
Is it causing null pointer exception?

**Comment by cer** [comment]
I prefer to run the CDC service separately but you can use the embedded version if you want.

**Comment by cer** [comment]
You should use the same version of Debezium that Eventuate Local uses: debeziumVersion=0.3.6
It's only been tested with the older version.
We haven't invested time upgrading to the newer version because Eventuate Local is moving away from Debezium.

There are some configuration properties: See the environment variables set here: https://github.com/eventuate-examples/eventuate-examples-java-spring-todo-list/blob/master/single-module/docker-compose-eventuate-local.yml#L28
